name: foodbuddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.1  # Updated
  firebase_auth: ^4.19.2  # Updated
  cloud_firestore: ^4.15.3  # Updated
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  # Map functionality
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  http: ^1.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  # Enhanced UI components
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  # For map markers and clustering
  flutter_map_marker_cluster: ^1.3.6
  # File picker for photo selection (more reliable than image_picker)
  file_picker: ^8.0.0+1
  # Camera package for taking photos
  camera: ^0.10.5+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets for Google Maps credentials and demo images
  assets:
    - assets/credentials/
    - assets/demo_images/